package com.mmfsin.oneworld.domain.models

data class Event(
    var id: String,
    var category: Int,
    var image: String,
    var title: String,
    var description: String?,
    var webUrl: String?,
    var creatorId: String,
    var creatorName: String,
    var date: Long,
    var hour: Int,
    var minutes: Int,
    var address: String,
    var likesCount: Int,
    var userLiked: Boolean,
    var savesCount: Int,
    var userSaved: Boolean,
    var attendeesCount: Int,
    var userAttending: Boolean,
)

fun getExampleEvents() = listOf(
    Event(
        id = "1",
        category = 2,
        image = "",
        title = "Titulo de Evento",
        description = "Descripción de evento ",
        creatorId = "",
        creatorName = "Mufasa Mufasín",
        date = 32413541,
        hour = 12,
        minutes = 34,
        address = "c/Antonio Lopez 67, Madrid",
        webUrl = "estereotipia.com",
        likesCount = 234,
        userLiked = true,
        savesCount = 12,
        userSaved = false,
        attendeesCount = 2432,
        userAttending = true
    ),
    Event(
        id = "2",
        category = 3,
        image = "",
        title = "Titulo de Evento 2",
        description = "Descripción de evento 2",
        creatorId = "",
        creatorName = "Alberto Chicote",
        date = 3241343,
        hour = 5,
        minutes = 12,
        address = "c/Peralta del Río, Madrid",
        webUrl = null,
        likesCount = 12,
        userLiked = false,
        savesCount = 1,
        userSaved = true,
        attendeesCount = 2,
        userAttending = false
    ),
)
